check50:
  dependencies:
    - check50-java
    - check50-junit
  files:
    - !exclude "*"
    - !include "*.java"

submit50:
  slug: "liv-ac-uk/comp122/2021/polymorphism"
  files:
    - !exclude "*"
    - !include "*.java"