check50: 
  dependencies:
    - check50-java
    - check50-checkstyle


  files: &check50_files
    - !exclude "*"
    - !require StringTools.java
    - !include "docs/index.html"

submit50:
  files: *check50_files
