check50:
  dependencies:
    - check50-java
    - check50-junit
  files: &check50_files
    - !exclude "*"
    - !require "CShanty.java"
    - !require "Factorial.java"
    - !require "Largest.java"
    - !require "Comp122.class"


submit50:
  slug: "liv-ac-uk/comp122/2021/arrayLoops"
  files: *check50_files