lab50:
  files:
    - !exclude "*"
    - !include "Declarations.java"
    - !include "FPTestApp.java"
    - !include "SimpleCircle.java"
    - !include "Pythagoras.java"
    - !include "Cosines.java"
    
  window:
    - editor
    - readme
    - terminal
