lab50:
  files:
    - !exclude "*"
    - !include "Terminal.class"
    - !include "Largest.java"
    - !include "Factorial.java"
    - !include "Hello.java"
    
  window:
    - editor
    - readme
    - terminal