check50:
  dependencies:
    - check50-java
  files:
    - !exclude "*"
    - !include "LeapYear.java"
    - !include "Terminal.class"

submit50:
  slug: "liv-ac-uk/comp122/2021/leapYears"
  files:
    - !exclude "*"
    - !include "LeapYear.java"
